# -*- coding: utf-8 -*-
"""
/***************************************************************************
 procplug1
                                 A QGIS plugin
 This is a first attempt at a processing plugin for the O&P Project Initiation GUI
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-06-16
        copyright            : (C) 2023 by Tyler Martin
        email                : tyler.smconsulting@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Tyler Martin'
__date__ = '2023-06-16'
__copyright__ = '(C) 2023 by Tyler Martin'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load procplug1 class from file procplug1.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .projinit import procplug1Plugin
    return procplug1Plugin()
